import { supabase } from "./supabase.js";

// ---------------------------------------------------------------------------
// Data-access layer. The DB uses snake_case and separate tables; the UI keeps
// the prototype's camelCase shape ({ donorId, receipt, paidTo, ... }). These
// mappers translate at the boundary so the UI code barely changes.
// ---------------------------------------------------------------------------
const mapDonor = (r) => ({
  id: r.id, name: r.name, phone: r.phone, city: r.city || "", pan: r.pan || "", lang: r.lang || "en",
});
const mapDonation = (r) => ({
  id: r.id, donorId: r.donor_id, amount: r.amount, date: r.date, mode: r.mode, purpose: r.purpose,
  receipt: r.receipt_no, source: r.source, notes: r.notes || "", createdBy: r.created_by, createdAt: r.created_at,
});
const mapExpense = (r) => ({
  id: r.id, amount: r.amount, date: r.date, category: r.category, paidTo: r.paid_to || "",
  mode: r.mode, notes: r.notes || "", createdBy: r.created_by, createdAt: r.created_at,
});

// Load the whole ledger in one shot. The dataset is small (single foundation),
// so refetching after each mutation keeps state trivially consistent.
export async function loadAll() {
  const [donors, donations, expenses, settings] = await Promise.all([
    supabase.from("donors").select("*").order("created_at", { ascending: true }),
    supabase.from("donations").select("*").order("date", { ascending: false }),
    supabase.from("expenses").select("*").order("date", { ascending: false }),
    supabase.from("settings").select("*"),
  ]);
  const error = donors.error || donations.error || expenses.error || settings.error;
  if (error) throw error;
  return {
    donors: donors.data.map(mapDonor),
    donations: donations.data.map(mapDonation),
    expenses: expenses.data.map(mapExpense),
    settings: Object.fromEntries((settings.data || []).map((s) => [s.key, s.value])),
  };
}

// Resolve a donor: use the picked id, else match an existing phone, else create.
async function resolveDonor({ donorId, name, phone, city, pan }) {
  if (donorId) return donorId;

  const { data: existing, error: findErr } = await supabase
    .from("donors").select("id").eq("phone", phone).maybeSingle();
  if (findErr) throw findErr;
  if (existing) return existing.id;

  const { data, error } = await supabase
    .from("donors")
    .insert({ name: name.trim(), phone, city: city || "", pan: pan || "", lang: "en" })
    .select("id")
    .single();
  if (error) throw error;
  return data.id;
}

export async function addDonation(form) {
  const donorId = await resolveDonor(form);
  // receipt_no is generated by the DB trigger; source/created_by default server-side.
  const { data, error } = await supabase
    .from("donations")
    .insert({
      donor_id: donorId,
      amount: Number(form.amount),
      date: form.date,
      mode: form.mode,
      purpose: form.purpose,
      notes: form.notes || "",
    })
    .select("*")
    .single();
  if (error) throw error;

  const { data: donorRow, error: dErr } = await supabase
    .from("donors").select("*").eq("id", donorId).single();
  if (dErr) throw dErr;
  return { donation: mapDonation(data), donor: mapDonor(donorRow) };
}

export async function updateDonation(id, form) {
  // Editing can also reassign / create a donor if a new name+phone was entered.
  let donorId = form.donorId;
  if (!donorId && form.name && /^\d{10}$/.test(form.phone)) {
    donorId = await resolveDonor(form);
  }
  const patch = {
    amount: Number(form.amount), date: form.date, mode: form.mode, purpose: form.purpose, notes: form.notes || "",
  };
  if (donorId) patch.donor_id = donorId;
  const { data, error } = await supabase
    .from("donations").update(patch).eq("id", id).select("*").single();
  if (error) throw error;
  return mapDonation(data);
}

export async function deleteDonation(id) {
  const { error } = await supabase.from("donations").delete().eq("id", id);
  if (error) throw error;
}

export async function addExpense(form) {
  const { data, error } = await supabase
    .from("expenses")
    .insert({
      amount: Number(form.amount), date: form.date, category: form.category,
      paid_to: form.paidTo || "", mode: form.mode, notes: form.notes || "",
    })
    .select("*")
    .single();
  if (error) throw error;
  return mapExpense(data);
}

export async function updateExpense(id, form) {
  const { data, error } = await supabase
    .from("expenses")
    .update({
      amount: Number(form.amount), date: form.date, category: form.category,
      paid_to: form.paidTo || "", mode: form.mode, notes: form.notes || "",
    })
    .eq("id", id)
    .select("*")
    .single();
  if (error) throw error;
  return mapExpense(data);
}

export async function deleteExpense(id) {
  const { error } = await supabase.from("expenses").delete().eq("id", id);
  if (error) throw error;
}
